version: '3'

services:
  web:
    image: odoo:15
    container_name: odoo
    env_file: .env
    ports:
      - "8069:8069"
      - "20016:8072"
    depends_on:
      - db
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./extra-addons:/mnt/extra-addons
    command: -- 

  db:
    image: postgres:latest
    env_file: .env
    container_name: postgres
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-web-data:
  odoo-db-data:
